added step to use set_version

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -118,8 +118,11 @@ runs:
           echo "SnapshotVersion=$((${{steps.splitVersionMinor.outputs._0}} + 1)).0.0-SNAPSHOT" >> $GITHUB_OUTPUT
          elif [ $RELEASE_TYPE == 'minor' ]; then
           echo "SnapshotVersion=${{steps.splitVersionMinor.outputs._0}}.$((${{steps.splitVersionMinor.outputs._1}} + 1)).0-SNAPSHOT" >> $GITHUB_OUTPUT
-         else 
-           echo "SnapshotVersion=${{steps.splitVersionMinor.outputs._0}}.${{steps.splitVersionMinor.outputs._1}}.$((${{steps.splitVersionMinor.outputs._2}} + 1))-SNAPSHOT" >> $GITHUB_OUTPUT 
+         elif [ $RELEASE_TYPE == 'patch' ]; then
+          echo "SnapshotVersion=${{steps.splitVersionMinor.outputs._0}}.${{steps.splitVersionMinor.outputs._1}}.$((${{steps.splitVersionMinor.outputs._2}} + 1))-SNAPSHOT" >> $GITHUB_OUTPUT
+         else
+          echo "ERROR: Invalid version_type '${{ inputs.version_type }}'."
+          exit 1
          fi
       env:
         RELEASE_TYPE: ${{inputs.version_type}}
