Update action.yaml

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -1,6 +1,7 @@
-name: SemVer Release Action
-description: Automates semantic versioning and release.
+name: SemVer Release Version
+description: Utilized for creating releases of projects
 
+# Inputs
 inputs:
   version_type:
     description: "Version type to increment (major, minor, patch, select)"
@@ -9,10 +10,6 @@ inputs:
   set_version:
     description: "Set version number explicitly (e.g., 1.2.3). Leave empty to increment."
     required: false
-  trunk_branch_name:
-    description: "The main branch from which releases are made."
-    required: true
-    default: 'main'
   ikmdevops_pat:
     description: "PAT TOKEN for IKMDevops User"
     required: true
@@ -34,23 +31,17 @@ inputs:
   ossrh_token:
     description: "OSSRH Token"
     required: true
-
-outputs:
-  new_version:
-    description: "The new version number."
+  
 
 runs:
-  using: "composite"
+  using: "composite" 
   steps:
     - name: Checkout Repository
       uses: actions/checkout@v4
       with:
         token: ${{inputs.ikmdevops_pat}}
-        fetch-depth: 0  # Fetch all history to get all tags
-        ref: ${{ inputs.trunk_branch_name }}
-        persist-credentials: true
 
-    - name: Set up Java
+    - name: Setup Java
       uses: actions/setup-java@v4
       with:
         distribution: 'zulu'
@@ -61,182 +52,187 @@ runs:
         gpg-private-key: ${{ inputs.gpg_key }}
         gpg-passphrase: MAVEN_GPG_PASSPHRASE
 
-    - name: Verify SNAPSHOT Version
+    - name: Build Protoc Docker container
+      uses: docker/build-push-action@v6
+      if: github.event.repository.name == 'tinkar-schema'
+      with:
+        push: false
+        context: .
+        file: protoc.dockerfile
+        tags: tinkar-schema-protoc:latest
+  
+  
+    - name: Generate Java Code
+      if: github.event.repository.name == 'tinkar-schema'
       shell: bash
       run: |
-        CURRENT_POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
-        if [[ "$CURRENT_POM_VERSION" != *-SNAPSHOT ]]; then
-          echo "ERROR: The current version in pom.xml ($CURRENT_POM_VERSION) is not a SNAPSHOT version."
-          exit 1
-        fi
-
-    - name: Determine Release Version
-      id: release_version
-      shell: bash
-      run: |
-        # Remove '-SNAPSHOT' from current pom version
-        CURRENT_POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
-        RELEASE_VERSION=${CURRENT_POM_VERSION%-SNAPSHOT}
-        echo "Release version: $RELEASE_VERSION"
-        echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT
-
-    - name: Update Maven Project Version to Release Version
-      shell: bash
-      run: |
-        mvn versions:set -DnewVersion=${{ steps.release_version.outputs.release_version }} -DgenerateBackupPoms=false
-        echo "After setting release version"
-        git status
-
-    - name: Commit Release Version Change
-      shell: bash
-      run: |
-        git config user.name "ikmdevops"
-        git config user.email ${{inputs.ikmdevops_email}}
-        git add pom.xml
-        git commit -m "Prepare release version ${{ steps.release_version.outputs.release_version }}"
-        git push origin HEAD:${{ inputs.trunk_branch_name }}
-
-    - name: Create and Push Tag
-      shell: bash
-      run: |
-        git tag -a v${{ steps.release_version.outputs.release_version }} -m "Release v${{ steps.release_version.outputs.release_version }}"
-        git push origin v${{ steps.release_version.outputs.release_version }}
+        sudo docker run -v ./src/main/java-generated:/home/proto-builder/src/main/java-generated --rm tinkar-schema-protoc:latest
         
+    - name: list java code
+      if: github.event.repository.name == 'tinkar-schema'
+      shell: bash
+      run: |
+        ls src/main/java-generated
+
+    - name: Extract Version
+      id: get_current_version
+      shell: bash
+      run: |
+          echo "POM_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
+
+    - name: Print Maven POM project version
+      shell: bash
+      run: |
+        echo "version = ${{ steps.get_current_version.outputs.POM_VERSION }}"
+
+    - name: Verify Is SNAPSHOT Version
+      if: ${{ !contains(steps.get_current_version.outputs.POM_VERSION, '-SNAPSHOT')}}
+      shell: bash
+      run: |
+        echo "ERROR: Version is set to incompatible version ${{steps.get_current_version.outputs.POM_VERSION}}. Only SNAPSHOT development versions can be converted to a release version."
+        exit 1
+
+    - name: Split version code
+      uses: xom9ikk/split@v1.1
+      id: splitCurrentVersion
+      with:
+        string: ${{steps.get_current_version.outputs.POM_VERSION}}
+        separator: '-'
+        limit: -1
+
+    - name: Split version code - Separate By .
+      uses: xom9ikk/split@v1.1
+      id: splitVersionMinor
+      with:
+        string: ${{steps.splitCurrentVersion.outputs._0}}
+        separator: .
+        limit: -1
+
+    - name: Increment Snapshot Version
+      id: nextSnapshotVersion
+      shell: bash
+      run: |
+         if [ $SET_NEXT_VERSION != '' ]; then
+          echo "SnapshotVersion=$SET_NEXT_VERSION" >> $GITHUB_OUTPUT
+         elif [ $RELEASE_TYPE == 'major' ]; then
+          echo "SnapshotVersion=((${{steps.splitVersionMinor.outputs._0}} + 1)).0.0-SNAPSHOT" >> $GITHUB_OUTPUT
+         elif [ $RELEASE_TYPE == 'minor' ]; then
+          echo "SnapshotVersion=${{steps.splitVersionMinor.outputs._0}}.$((${{steps.splitVersionMinor.outputs._1}} + 1)).0-SNAPSHOT" >> $GITHUB_OUTPUT
+         else 
+           echo "SnapshotVersion=${{steps.splitVersionMinor.outputs._0}}.${{steps.splitVersionMinor.outputs._1}}.$((${{steps.splitVersionMinor.outputs._2}} + 1))-SNAPSHOT" >> $GITHUB_OUTPUT 
+         fi
+      env:
+        RELEASE_TYPE: ${{inputs.version_type}}
+        SET_NEXT_VERSION: ${{inputs.set_version}}
+
+    - name: Print Information
+      shell: bash
+      run: |
+        echo "Release Version -- ${{steps.splitCurrentVersion.outputs._0}}"
+        echo "Snapshot Version -- ${{steps.nextSnapshotVersion.outputs.SnapshotVersion}}"
+          
+    - name: Print Versions
+      shell: bash
+      run: |
+        echo "Release Version: ${{steps.splitCurrentVersion.outputs._0}}"
+        echo "Next Snapshot Versin: ${{steps.nextSnapshotVersion.outputs.SnapshotVersion}}"
+        echo "RELEASE ENV -- $RELEASE_VERSION"
+
+    - name: Set Release Version
+      shell: bash
+      run: |
+          ./mvnw \
+          --batch-mode \
+          -U \
+          versions:set \
+          -DnewVersion=${{steps.splitCurrentVersion.outputs._0}} \
+          -DgenerateBackupPoms=false \
+          -Dmaven.build.cache.enabled=false
+
+    - name: Build Release Version
+      shell: bash
+      run: |
+           ./mvnw clean install \
+                --batch-mode \
+                -e \
+                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
+                -PcodeQuality,release-enforcement \
+                -Dmaven.build.cache.enabled=false
+
+    - name: Create tag
+      shell: bash
+      run: |
+           git remote set-url origin https://git:${{inputs.ikmdevops_pat}}@github.com/${{github.repository}}.git
+           git pull -p
+           git add .
+           git config user.name "ikmdevops"
+           git config user.email ${{inputs.ikmdevops_email}}
+           git commit -m 'Release ${{steps.splitCurrentVersion.outputs._0}}'
+           git tag -a ${{steps.splitCurrentVersion.outputs._0}} -m '${{steps.splitCurrentVersion.outputs._0}}' --force
+
+    - name: Set Dev Version
+      shell: bash
+      run: |
+          ./mvnw -B versions:set \
+          -DnewVersion=${{steps.nextSnapshotVersion.outputs.SnapshotVersion}} \
+          -DgenerateBackupPoms=false \
+          --batch-mode
+
+    - name: Commit & Push
+      shell: bash
+      run: |
+           git add .
+           git commit -m 'Set next dev version to ${{steps.nextSnapshotVersion.outputs.SnapshotVersion}}'
+           git push origin HEAD:main
+           git push --tags origin
+
     - name: Create Release
       shell: bash
       id: create_release
       run: |
-        curl -L \
-         -X POST \
-         -H "Accept: application/vnd.github+json" \
-         -H "Authorization: Bearer ${{inputs.github_token}}" \
-         -H "X-GitHub-Api-Version: 2022-11-28" \
-         https://api.github.com/repos/${{github.repository}}/releases \
-        -d '{"tag_name":"${{ steps.release_version.outputs.release_version }}","name":"Release ${{ steps.release_version.outputs.release_version }}","body":"Release ${{ steps.release_version.outputs.release_version }}","draft":false,"prerelease":false,"generate_release_notes":false}'
-
-    - name: Output New Version
-      shell: bash
-      run: echo "Released version ${{ steps.release_version.outputs.release_version }}"
+          curl -L \
+           -X POST \
+           -H "Accept: application/vnd.github+json" \
+           -H "Authorization: Bearer ${{inputs.github_token}}" \
+           -H "X-GitHub-Api-Version: 2022-11-28" \
+           https://api.github.com/repos/${{github.repository}}/releases \
+          -d '{"tag_name":"${{steps.splitCurrentVersion.outputs._0}}","name":"Release ${{steps.splitCurrentVersion.outputs._0}}","body":"Release ${{steps.splitCurrentVersion.outputs._0}}","draft":false,"prerelease":false,"generate_release_notes":false}'
 
     - name: Checkout Code Repository
       uses: actions/checkout@v4
       if: github.event.repository.name != 'tinkar-schema' && github.event.repository.name != 'komet'
       with:
-        ref: ${{ inputs.trunk_branch_name }}
-        persist-credentials: true
+        ref: ${{steps.splitCurrentVersion.outputs._0}}
 
     - name: Maven Build
       shell: bash
       if: github.event.repository.name != 'tinkar-schema' && github.event.repository.name != 'komet'
       run: |
-        ./mvnw clean install -U \
-         --batch-mode \
-         -e \
-         -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
-         -Dmaven.build.cache.enabled=false \
-         -PcodeQuality
+       ./mvnw clean install -U \
+        --batch-mode \
+        -e \
+        -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
+        -Dmaven.build.cache.enabled=false \
+        -PcodeQuality
 
     - name: Publish To OSSRH (Maven Central Staging)
       shell: bash
       if: github.event.repository.name != 'tinkar-schema' && github.event.repository.name != 'komet'
       run: |
-        ./mvnw deploy -U\
-            --batch-mode \
-            -e \
-            -U \
-            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
-            -DskipTests \
-            -DskipITs \
-            -Dmaven.main.skip \
-            -Dmaven.test.skip \
-            -DrepositoryId=ossrh \
-            -DrepositoryIdOSSRH='true' \
-            -PstageOSSRH \
-            -Dmaven.build.cache.enabled=false
-         env:
-           MAVEN_USERNAME: ${{ inputs.ossrh_username }}
-           MAVEN_CENTRAL_TOKEN: ${{ inputs.ossrh_token }}
-           MAVEN_GPG_PASSPHRASE: ${{ inputs.gpg_passphrase }}
-
-    # - name: Pull Latest Changes Before Next Snapshot Version
-    #   shell: bash
-    #   run: |
-    #     # Ensure the local branch is up-to-date before making new changes
-    #     git fetch origin ${{ inputs.trunk_branch_name }}
-    #     git checkout ${{ inputs.trunk_branch_name }}
-    #     # git reset --hard origin/${{ inputs.trunk_branch_name }}
-
-    - name: Determine Next Snapshot Version
-      id: next_snapshot_version
-      shell: bash
-      run: |
-        VERSION_TYPE="${{ inputs.version_type }}"
-        SET_VERSION="${{ inputs.set_version }}"
-        RELEASE_VERSION="${{ steps.release_version.outputs.release_version }}"
-        
-        # Split the release version into components
-        IFS='.' read -r MAJOR MINOR PATCH <<< "$RELEASE_VERSION"
-        
-        if [ -n "$SET_VERSION" ]; then
-        # If set_version is provided, increment based on it
-        NEXT_SNAPSHOT_VERSION="${SET_VERSION}-SNAPSHOT"
-        else
-        # Validate that version_type is one of the allowed values
-        if [[ "$VERSION_TYPE" != "major" && "$VERSION_TYPE" != "minor" && "$VERSION_TYPE" != "patch" ]]; then
-         echo "Invalid version_type specified: $VERSION_TYPE. Must be 'major', 'minor', or 'patch'."
-         exit 1
-        fi
-        
-        case "$VERSION_TYPE" in
-         major)
-           MAJOR=$((MAJOR + 1))
-           MINOR=0
-           PATCH=0
-           ;;
-         minor)
-           MINOR=$((MINOR + 1))
-           PATCH=0
-           ;;
-         patch)
-           PATCH=$((PATCH + 1))
-           ;;
-        esac
-        
-        NEXT_SNAPSHOT_VERSION="${MAJOR}.${MINOR}.${PATCH}-SNAPSHOT"
-        fi
-        
-        echo "Next snapshot version: $NEXT_SNAPSHOT_VERSION"
-        echo "next_snapshot_version=$NEXT_SNAPSHOT_VERSION" >> $GITHUB_OUTPUT
-
-    - name: Update Maven Project Version to Next Snapshot Version
-      shell: bash
-      run: |
-        echo "Before updating next snapshot version:"
-        cat pom.xml
-        mvn versions:set -DnewVersion=${{ steps.next_snapshot_version.outputs.next_snapshot_version }} -DgenerateBackupPoms=false -DprocessAllModules
-        echo "After setting next snapshot version"
-        cat pom.xml
-
-    - name: Git Status After Version Update
-      shell: bash
-      run: |
-        git status
-        git diff
-
-    - name: Commit Next Snapshot Version Change
-      shell: bash
-      run: |
-        git config user.name "ikmdevops"
-        git config user.email ${{inputs.ikmdevops_email}}
-        git add pom.xml
-        git commit -m "Prepare for next development iteration ${{ steps.next_snapshot_version.outputs.next_snapshot_version }}"
-        
-        # pull latest changes and rebase before pushing
-        git pull --rebase origin ${{ inputs.trunk_branch_name }}
-        git push origin HEAD:${{ inputs.trunk_branch_name }}
-
-    - name: Output Release Information
-      shell: bash
-      run: |
-        echo "Released version ${{ steps.release_version.outputs.release_version }}"
-        echo "Updated to next snapshot version ${{ steps.next_snapshot_version.outputs.next_snapshot_version }}"
+          ./mvnw deploy -U\
+              --batch-mode \
+              -e \
+              -U \
+              -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
+              -DskipTests \
+              -DskipITs \
+              -Dmaven.main.skip \
+              -Dmaven.test.skip \
+              -DrepositoryId=ossrh \
+              -DrepositoryIdOSSRH='true' \
+              -PstageOSSRH \
+              -Dmaven.build.cache.enabled=false
+      env:
+        MAVEN_USERNAME: ${{ inputs.ossrh_username }}
+        MAVEN_CENTRAL_TOKEN: ${{ inputs.ossrh_token }}
+        MAVEN_GPG_PASSPHRASE: ${{ inputs.gpg_passphrase }}
